from langchain_core.messages import AIMessage
from grid_balancer.state import AgentState

def supervisor_agent(state: AgentState):
    """
    Supervisor Agent node.
    Monitors telemetry and coordinates tasks by deciding which agent runs next.
    """
    telemetry = state.get("telemetry", {})
    forecast = state.get("forecast", {})
    recommendations = state.get("recommendations", {})
    
    hour = telemetry.get("hour", 0)
    temp = telemetry.get("temperature", 20.0)
    weather = telemetry.get("weather", "sunny")
    freq = telemetry.get("frequency_hz", 50.0)
    status = telemetry.get("status", "STABLE")
    
    # Base analysis message
    analysis = (
        f"Supervisor Analysis at Hour {hour:02d}:00 | Temperature: {temp}°C | Weather: {weather} | "
        f"Frequency: {freq}Hz (Status: {status})\n"
    )
    
    if not forecast:
        # Step 1: Delegate to Forecaster
        reasoning = (
            f"{analysis}"
            f"-> Telemetry received. Grid frequency is {freq}Hz. "
            f"Historical RAG data is required to forecast load patterns for the next hour. "
            f"Delegating to Forecaster Agent."
        )
        next_step = "forecaster"
    elif not recommendations:
        # Step 2: Delegate to Optimizer
        reasoning = (
            f"{analysis}"
            f"-> Forecast received (Predicted Gen: {forecast.get('predicted_generation')}MW, "
            f"Predicted Demand: {forecast.get('predicted_demand')}MW). "
            f"Control heuristics must be applied to balance power outputs and stabilize frequency. "
            f"Delegating to Optimizer Agent."
        )
        next_step = "optimizer"
    else:
        # Step 3: Optimization complete
        reasoning = (
            f"{analysis}"
            f"-> Rebalancing plan generated by Optimizer. Battery adjustment: "
            f"{recommendations.get('Battery_Storage_F', 0.0)}MW, Fossil Fuel adjustment: "
            f"{recommendations.get('Fossil_Fuel_Plant_E', 0.0)}MW. "
            f"Grid balance checks out. Ending simulation step."
        )
        next_step = "__end__"
        
    print(f"\n[Supervisor Agent]: {reasoning}")
    
    # We append the supervisor's AIMessage to the message log
    new_messages = list(state.get("messages", []))
    new_messages.append(AIMessage(content=reasoning, name="Supervisor"))
    
    return {
        "messages": new_messages,
        "next_agent": next_step
    }
